name: Check UPC Status
on:
  workflow_dispatch:
  schedule:
    - cron: "0 13,18,23 * * *"

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install chromium
          playwright install-deps chromium

      - name: Execute script
        env:
          UPC_USER: ${{ secrets.UPC_USER }}
          UPC_PASS: ${{ secrets.UPC_PASS }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py

      - name: Save Screenshot
        uses: actions/upload-artifact@v4
        with:
          name: status-report
          path: status_tesis_*.png
          retention-days: 7
